---
- name: Perform ECR login.
  shell: "$(aws ecr get-login --no-include-email --region {{ ecr_region }})"
  tags: ['skip_ansible_lint']

- name: Ensure ECR repo exists.
  ecs_ecr:
    name: "{{ ecr_image_name }}"
    region: "{{ ecr_region }}"
    registry_id: "{{ ecr_account_id }}"
    state: present
