---
- name: Set the current image tag.
  set_fact:
    image_tag: "{{ outer_item }}"

- name: Print the current tag being pushed.
  debug: var=image_tag

- name: Ensure there's not already an image locally tagged with the ecr_url.
  docker_image:
    name: "{{ ecr_url }}/{{ ecr_image_name }}:{{ image_tag }}"
    state: absent
    force: true

- name: Apply additional tag if there's more than one.
  docker_image:
    name: "{{ ecr_image_name }}:{{ ecr_image_tags.0 }}"
    repository: "{{ ecr_image_name }}:{{ image_tag }}"
    state: present
    pull: false
  when: ecr_image_tags.0 != image_tag

- name: Push image to ECR.
  shell: "docker push {{ ecr_url }}/{{ ecr_image_name }}:{{ image_tag }}"
  register: push_result
  until: push_result is success
  retries: 10
  delay: 2
